name:                writescheme
version:             0.1.0.0
github:              "jowalski/writescheme"
license:             BSD3
author:              "John Kowalski"
maintainer:          "jowalski@gmail.com"
copyright:           "Copyright (c) 2018 John Kowalski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/jowalski/writescheme#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- array
- mtl

library:
  source-dirs: src

executables:
  writescheme-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - writescheme
    - QuickCheck

tests:
  writescheme-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - writescheme
    - QuickCheck
